### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by stevebail** [ncclient/ncclient#421] opened 2020-08-14 12:09 UTC
Any plans to support TLS 1.2/1.3?
If not, any suggestions to "add" TLS to the ncclient library?
Thanks.

**Comment by einarnn** [comment] 2020-08-15 21:29
> Any plans to support TLS 1.2/1.3?
> 
> If not, any suggestions to "add" TLS to the ncclient library?
> 
> Thanks.

No, no active plans to add TLS support. Please feel free to propose its addition via a pull request.

Cheers,

Einar

**Comment by nickbroon** [comment] 2021-12-20 13:26
Possible duplicate of #271  ?

**Comment by einarnn** [comment] 2021-12-28 11:24
@nickbroon, yes, a duplicate of #271. Closing this one off.

**Closed by einarnn** 2021-12-28 11:24 UTC
